### ISSUE TITLE
Word.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-oogunjimi/Urban-Dictionary#13]
Line 6, You don't need the backslash in that case, it would still work.

There should be a space between line 28 and 29

There should be a space between line 31 and 32

There should be a space between line 34 and 35

There should be a space between line 37 and 38

**Comment by unicodeveloper** [comment]
Why have you not taken care of this issue?

**Comment by andela-oogunjimi** [comment]
The backslash has been removed.

**Comment by andela-oogunjimi** [comment]
I have taken care of the issues.
