### ISSUE TITLE
DatabaseTest.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-oogunjimi/Urban-Dictionary#19]
Please be consistent. Stop switching between the different types of array declarations.

Choose one struggle [] or array();

We have the [setUp](https://phpunit.de/manual/current/en/fixtures.html) and tearDown methods in PHPUnit testing.

You can use them to create data or functions or instances you will need throughout the testing instead of replicating it in each test.

Many of the methods here dont have legible code.

It's hard to understand what's going on , so space them well and if a method is doing too much, look for how to abstract it into several methods that will make it more readable

**Comment by unicodeveloper** [comment]
You are not testing for expectations here yet I see `@expectedException Exception`

**Comment by unicodeveloper** [comment]
Why haven't you taken care of this?

**Comment by andela-oogunjimi** [comment]
Exceptions are being tested in these methods. A setup method has been added.
